# Generated by Django 4.2.16 on 2025-10-23 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(help_text='Código único de identificación del empleado', max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nombre', models.CharField(blank=True, max_length=30, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, max_length=30, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('ubicacion', models.CharField(choices=[('santiago', 'Santiago'), ('valparaiso', 'Valparaíso'), ('concepcion', 'Concepción'), ('antofagasta', 'Antofagasta'), ('temuco', 'Temuco'), ('iquique', 'Iquique'), ('rancagua', 'Rancagua'), ('talca', 'Talca'), ('osorno', 'Osorno'), ('puerto_montt', 'Puerto Montt'), ('punta_arenas', 'Punta Arenas'), ('arica', 'Arica')], default='santiago', max_length=20, verbose_name='Ubicación')),
                ('departamento', models.CharField(choices=[('administracion', 'Administración'), ('ventas', 'Ventas'), ('operaciones', 'Operaciones'), ('soporte', 'Soporte Técnico'), ('marketing', 'Marketing'), ('rrhh', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('logistica', 'Logística'), ('ti', 'Tecnologías de la Información'), ('calidad', 'Aseguramiento de Calidad')], default='operaciones', max_length=20, verbose_name='Departamento')),
                ('puesto', models.CharField(blank=True, help_text='Cargo que desempeña el empleado', max_length=100, verbose_name='Puesto')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Emergencia')),
                ('nombre_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto de Emergencia')),
                ('email_personal', models.EmailField(blank=True, help_text='Correo electrónico personal del empleado', max_length=254, verbose_name='Correo Personal')),
                ('linkedin', models.URLField(blank=True, verbose_name='Perfil de LinkedIn')),
                ('prevision', models.CharField(choices=[('fonasa', 'FONASA'), ('isapre_banmedica', 'Isapre Banmédica'), ('isapre_colmena', 'Isapre Colmena'), ('isapre_consalud', 'Isapre Consalud'), ('isapre_cruz_blanca', 'Isapre Cruz Blanca'), ('isapre_vida_tres', 'Isapre Vida Tres')], default='fonasa', max_length=30, verbose_name='Previsión')),
                ('afp', models.CharField(choices=[('afp_capital', 'AFP Capital'), ('afp_provida', 'AFP Provida'), ('afp_habitat', 'AFP Habitat'), ('afp_planvital', 'AFP PlanVital'), ('afp_cuprum', 'AFP Cuprum'), ('afp_modelo', 'AFP Modelo'), ('afp_uno', 'AFP Uno')], default='afp_capital', max_length=30, verbose_name='AFP')),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Base')),
                ('dias_vacaciones_anuales', models.PositiveIntegerField(default=15, verbose_name='Días de vacaciones anuales')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto del empleado para su perfil', null=True, upload_to='tecnicos/fotos/', verbose_name='Foto de Perfil')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el empleado está actualmente activo en la empresa', verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'En Vacaciones'), ('licencia', 'En Licencia'), ('prueba', 'Período de Prueba')], default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tecnicos/fotos/')),
                ('postre_favorito', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(blank=True, to='tecnicos.especialidad')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
                'permissions': [('view_empleados', 'Puede ver el listado de empleados'), ('export_empleados', 'Puede exportar datos de empleados')],
            },
        ),
        migrations.CreateModel(
            name='VacacionesTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_aprobacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Vacaciones de Técnico',
                'verbose_name_plural': 'Vacaciones de Técnicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cv', 'Curriculum Vitae'), ('certificado', 'Certificado'), ('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='tecnicos/documentos/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Documento de Técnico',
                'verbose_name_plural': 'Documentos de Técnicos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
