# Generated by Django 4.2.16 on 2025-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='salario_base',
        ),
        migrations.AlterField(
            model_name='documentotecnico',
            name='tipo',
            field=models.CharField(choices=[('cv', 'Curriculum Vitae'), ('contrato', 'Contrato'), ('anexo', 'Anexos'), ('certificado_vacaciones', 'Certificado de Vacaciones'), ('liquidacion_sueldo', 'Liquidación de Sueldo'), ('carta_amonestacion', 'Carta de Amonestación'), ('informe', 'Informes'), ('finiquito', 'Finiquito'), ('identificacion', 'Identificación'), ('otro', 'Otro')], max_length=25),
        ),
    ]
